#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'


#!/bin/sh
  . "$(dirname "$0")/_/husky.sh"

  commit_msg_file="$1"

  # 제목 형식: [문서]깃 Hook기능 추가
    if ! grep -qE '^\[(개발|수정|추가|삭제|리팩터링|문서|테스트|설정)\][[:space:]]*.+$' "$commit_msg_file"; then
        echo "커밋 제목 형식이 올바르지 않습니다."
        echo "예시: [문서]깃 Hook기능 추가"
        exit 1
    fi

  # 본문 최소 2줄 검사
  body_lines=$(awk '
      NR > 1 && $0 !~ /^[[:space:]]*$/ && $0 !~ /^#/ {
          count++
      }
      END {
          print count + 0
      }
  ' "$commit_msg_file")

   if [ "$body_lines" -lt 1 ]; then
       echo "커밋 본문을 최소 1줄 작성해야 합니다."
       exit 1
   fi

  exit 0